# Hello World!
- https://en.wikipedia.org/wiki/Hello_world

In [1]:
print(("Hello world!", print))
display(("Hello world!", display))
"Hello world!"

('Hello world!', <built-in function print>)


('Hello world!',
 <function IPython.core.display_functions.display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)>)

'Hello world!'

In [36]:
## Requirements (already specified in /requirements.txt (a Pip requirements.txt file))
## ($ pip install -r ./requirements.txt)
#!python -c 'import operator; assert operator'
#!python -c 'assert "sum" in dir(__builtins__)'; echo $?
#!pip install numpy
#!python -c 'import numpy; assert numpy'

0


## Arithmetic

In [10]:
def test_arithmetic_addition_python():
    assert 0 + 0 == 0
    assert 0 + 1 == 1
    assert 1 + 1 == 2
    assert 10 + 10 == 20
    assert 21 + 22 == 43
    assert 0 - 0 == 0
    assert 0 - 1 == -1
    assert 0 - 10 == -10
    assert -21 + -22 == -43
    assert -21 - 22  == -43
    assert 100 + 20 + 3 == 123

test_arithmetic_addition_python()

In [30]:
def test_arithmetic_addition_python_functional_operators():
    from operator import add, sub
    assert add(0, 0) == 0
    assert add(0, 1) == 1
    assert add(1, 1) == 2
    assert add(10, 10) == 20
    assert add(21, 22) == 43
    assert sub(0, 0) == 0
    assert sub(0, 1) == -1
    assert sub(0, 10) == -10
    assert add(-21, -22) == -43 == sub(-21, 22)
    assert sub(-21, 22)  == -43

    ## If we add(100, 20, 3), we get a TypeError:
    # with assertRaises(TypeError): # "add expected 2 arguments, got 3"
    #     assert add(100, 20, 3) == 123

    assert add(add(100, 20), 3) == 123 == sum((100, 20, 3)) == sum([100, 20, 3])
    assert 'sum' in dir(__builtins__)  # print(dir(__builtins__))
    assert sum((100, 20, 3)) == 123

test_arithmetic_addition_python_functional_operators()

In [28]:
def test_why_dont_we_need_to_import_the__sum__method():
    # dir?
    # display(dir(__builtins__))
    # display([attr for attr in dir(__builtins__)])
    display([attr for attr in dir(__builtins__) if attr.startswith('s')])
    display([attr for attr in dir(__builtins__) if attr.startswith('su')])

test_why_dont_we_need_to_import_the__sum__method()

['set', 'setattr', 'slice', 'sorted', 'staticmethod', 'str', 'sum', 'super']

['sum', 'super']

In [49]:
def test_arithmetic_addition_numpy():
    import numpy
    display(numpy.zeros(1))
    display(numpy.zeros(2))
    display(numpy.zeros((3, 3)))
    assert type(numpy.zeros(1)) == numpy.ndarray
    assert type(numpy.zeros((3, 3))) == numpy.ndarray

test_arithmetic_addition_numpy()

array([0.])

array([0., 0.])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])